
const api={
    prodDomain:"http://localhost:5050",
    devDomain:"http://localhost:5050",
    prodWsDomain:"ws://localhost:5051/ws",
    devWsDomain:"ws://localhost:5051/ws",
    checkCode:"/account/checkCode",
    Login:"/account/login",
    Register:"/account/register",
    getSysSetting:"/account/getSysSetting",
    loadMyGroup:"/group/loadMyGroup",
    saveGroup:"/group/saveGroup",
    getGroupInfo:"/group/getGroupInfo",
    getGroupInfo4Chat:"/group/getGroupInfo4Chat",
    dissoulutionGroup:"/group/dissolutionGroup",
    leaveGroup:"/group/leaveGroup",
    addOrRemoveGroupUser:"/group/addOrRemoveGroupUser",
    search:"/contact/search",
    applyAdd:"/contact/applyAdd",
    loadApply:"/contact/loadApply",
    dealWithApply:"/contact/dealWithApply",
    loadContact:"/contact/loadContact",
    getContactUserInfo:"/contact/getContactUserInfo",
    addContact2BlackList:"/contact/addContact2BlackList",
    delContact:"/contact/delContact",
    getContactInfo:"/contact/getContactInfo",
    saveUserInfo:"/userInfo/saveUserInfo",
    getUserInfo:"/userInfo/getUserInfo",
    updatePassword:"/userInfo/updatePassword",
    logout:"/userInfo/logout",
    sendMessage:"/chat/sendMessage",
    uploadFile:"/chat/uploadFile",
    loadAdminContact:"/admin/loadAdminContact",
    updateUserStatus:"/admin/updateUserStatus",
    forceOffline:"/admin/forceOffline",
    loadGroup:"/admin/loadGroup",
    adminDissolutionGroup:"/admin/dissolutionGroup",
    saveSysSetting:"/admin/saveSysSetting",
    getSysSeting4Admin:"/admin/getSysSeting",
    loadUpdateDataList:"/update/loadUpdateDataList",
    delUpdate:"/update/delUpdate",
    saveBeautAccount:"/admin/saveBeautAccount",
    delBeautAccount:"/admin/delBeautAccount",
    checkVersion:"/update/checkVersion",

}
 export default api;